version: "3"

services:
  backend:
    build: ./
    container_name: tatoo_container
    working_dir: /tatoo
    command:
      - ./commands/start_server.sh
    ports:
      - 8010:8008
    volumes:
      - ./src:/tatoo/src
    env_file:
      - .env

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
    env_file:
      - .env

volumes:
  pg_data: { }