# Generated by Django 4.1.1 on 2022-10-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="grade",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="progress",
        ),
    ]
