# Generated by Django 4.1.1 on 2022-10-25 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tatoo", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="Pinner",
        ),
        migrations.AlterField(
            model_name="pin",
            name="price",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
